# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('charset', models.CharField(blank=True, max_length=128)),
                ('h1', models.TextField(blank=True)),
                ('parsed_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('timeshift', models.TimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='urlinfo',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getter.URLs'),
        ),
    ]
