# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='timeshift',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
